import { readFileSync, writeFileSync } from 'node:fs';
const payload = readFileSync('samples/cl.json', 'utf8');
const base = 'http://127.0.0.1:9222';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
let idc = 0, SESSION = null;
function rpc(ws, m, p = {}) { return new Promise((res, rej) => { const id = ++idc; const on = (ev) => { const x = JSON.parse(ev.data); if (x.id === id) { ws.removeEventListener('message', on); x.error ? rej(new Error(x.error.message)) : res(x.result); } }; ws.addEventListener('message', on); const pl = { id, method: m, params: p }; if (SESSION) pl.sessionId = SESSION; ws.send(JSON.stringify(pl)); }); }
const ev = (e) => rpc(ws, 'Runtime.evaluate', { expression: e, returnByValue: true, awaitPromise: true }).then((r) => r.result && r.result.value);
const shot = async (f) => { const s = await rpc(ws, 'Page.captureScreenshot', { format: 'png' }); writeFileSync(f, Buffer.from(s.data, 'base64')); console.log('shot', f); };
const v = await (await fetch(`${base}/json/version`)).json();
const ws = new WebSocket(v.webSocketDebuggerUrl); await new Promise((r) => (ws.onopen = r));
const { targetId } = await rpc(ws, 'Target.createTarget', { url: 'http://localhost:5183/?screen=main' });
const att = await rpc(ws, 'Target.attachToTarget', { targetId, flatten: true }); SESSION = att.sessionId;
await rpc(ws, 'Runtime.enable'); await rpc(ws, 'Page.enable'); await sleep(4600);
const id = await ev(`(async()=>{const ctx=window.__ctx;const pa=await import('/src/project/projectAdapter.js');const store=await import('/src/project/store.js');const payload=${payload};const doc=pa.graphToDocument(payload,'VD');const pid='vd-'+Date.now();await store.saveProject(ctx.db,pa.normalizeProject({id:pid,name:'VD',documents:[doc],config:{enabledDocumentIds:[doc.id],disabledNodeIds:[],disabledRelationKeys:[],viewState:{}}}));return pid;})()`);
await rpc(ws, 'Page.navigate', { url: `http://localhost:5183/?screen=main&project=${id}` }); await sleep(5200);
const op = await ev(`(()=>{const ctx=window.__ctx;const n=ctx.model.nodes.find(x=>x.proofBody&&x.proofBody.length>10);if(!n)return 'none';const rec=ctx.modals.openFromNode(n,{x:0,y:0});if(rec&&rec.expandProof)rec.expandProof();ctx.graph.focusNode(n.id,1);return n.id;})()`);
await sleep(1500); await shot('C:/temp/vd-modal.png');
const rid = await ev(`(()=>{const ctx=window.__ctx;const r=ctx.model.nodes.find(n=>n.type==='reference'&&(ctx.model.usedBy.get(n.id)||new Set()).size>0)||ctx.model.nodes.find(n=>n.type==='reference');ctx.openDetails(r.id);return r.id;})()`);
await sleep(1000); await shot('C:/temp/vd-details.png');
console.log('opened', op, 'ref', rid); ws.close();
